### ISSUE TITLE
Dont work 18.08

### ISSUE THREAD

**Issue by furzich2015** [Gimenz/tiktok-downloader#1]
![image](https://user-images.githubusercontent.com/36245898/185394585-786ab1aa-7c9f-4597-87db-0c375874a625.png)

**Comment by Gimenz** [comment]
![image](https://user-images.githubusercontent.com/23699593/186199600-3d4c081d-7065-4722-b1d8-733e5bfd6f78.png)
try comment this code

**Comment by furzich2015** [comment]
Yes, I did it 3 days ago, I forgot to unsubscribe. Its work
