### ISSUE TITLE
[request] skip already downloaded videos

### ISSUE THREAD

**Issue by sideloading** [Gimenz/tiktok-downloader#2]
Hi, thanks for making this tool!

It would be good if it could skip any downloaded files, so if I need to re-run the tool for new posts, or missing posts, it can re-try and download only the missing videos.

Hope it makes sense!

**Comment by Gimenz** [comment]
i have added [307548a](https://github.com/Gimenz/tiktok-downloader/commit/307548a625d2cb350d6f27e5619d8cd1253e2416) feature to skip downloaded files, try it out. thanks
