### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'video')

### ISSUE THREAD

**Issue by snapboss** [Gimenz/tiktok-downloader#4]
The tool stopped working, I get this errors

Scraping All Video IDs
hasMore : true | 95 videos
hasMore : true | 96 videos
hasMore : false | 67 videos

Found 258 videos from @xxxxx

Start Downloading All Videos

TypeError: Cannot read properties of undefined (reading 'video')
    at getDownloadLink (C:\Users\xxx\Desktop\tiknew\handler.js:176:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async singleFile (C:\Users\xxx\Desktop\tiknew\handler.js:57:21)
task experienced an error { index: 1, id: 'xxxxx69424122498306' }

Any solution to fix this?

**Comment by Gimenz** [comment]
the api for getting video url from tiktok is now dead, try change the api

**Comment by snapboss** [comment]
> the api for getting video url from tiktok is now dead, try change the api

I changed the API but still have issues. The new API can be accessed only using Mobile User Agent, 
Api changed from  https://api.tiktokv.com/aweme/v1/aweme/detail/?aweme_id=${task.videoId}`;
to apiurl = `https://api-h2.tiktokv.com/aweme/v1/feed/?version_code=2613&aweme_id=${task.videoId}&device_type=Pixel%204`;

( The new working API : https://github.com/Tairraos/TikDown/commit/02a819e2d5509e83cccb858062798b08b7a7c1a0 )

and aweme_detail should now be replaced with aweme_list 

after replacing changing these to new API the tool still doesn't work :/

**Comment by Gimenz** [comment]
soon i will fix it, thanks for making issue

**Comment by Gimenz** [comment]
hi, i've fix it, you can try the new code. thanks :)

**Comment by snapboss** [comment]
> hi, i've fix it, you can try the new code. thanks :)

Works like a charn, thank you for your time and effort
