### ISSUE TITLE
Bypass the videos which give errors

### ISSUE THREAD

**Issue by snapboss** [Gimenz/tiktok-downloader#6]
Hello. I've been using your program for a while. 
Great job btw.

Sometimes the download stops due to API having issues or videos can't be downloaded and download stops for all the remaining videos.

Can you modify the code so even if some videos fail to download it continues with the other ones?

**Comment by Gimenz** [comment]
have you update with the latest commit?

**Comment by snapboss** [comment]
I am already on latest commit. 
I know it skips the downloaded files.

But the download stops if 1 file can't be downloaded. Some videos won't downloaded because they were posted using tiktok lite and the download always stops there

**Comment by Gimenz** [comment]
can you give screenshot?

**Comment by snapboss** [comment]
Screenshot : 
[https://i.imgur.com/R45qULm.png](https://i.imgur.com/R45qULm.png)
Error : 
TypeError: Cannot read properties of undefined (reading 'video')
    at getDownloadLink (C:\Users\menti\Desktop\tiktok-downloader-master\handler.js:182:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async singleFile (C:\Users\menti\Desktop\tiktok-downloader-master\handler.js:62:25)
task experienced an error { index: 18, id: '7093451841329040646' }

Video where download failed: https://www.tiktok.com/@chloetami21/video/7093451841329040646

As you can see this video was posted on Tiktok Lite , starting the download process again still gets stuck on this video.

**Comment by Gimenz** [comment]
sorry, i forgot to push.
but i've fixed, it should working for now
