### ISSUE TITLE
Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by snapboss** [Gimenz/tiktok-downloader#9]
Hello. The tool stopped working a few days ago. This is the error I am currently getting

>  Type a username/name :  tiktok
? Which Profile ? TikTok | @tiktok

> ##### [ User Info ] #####
> Username : @tiktok
> Nickname : TikTok
> Post : 488
> Private : false
> Bio : the 🕰 app
> Followers : 66M
> Following : 575

> ? is the data correct? Yes
> Scraping All Video IDs
> E:\TikTok\tiknew\index.js:77
>                     console.log('hasMore :', videoList.hasMore, '|', videoList.itemList.length, 'videos');
                                                                                        ^

> TypeError: Cannot read properties of undefined (reading 'length')
  >   at E:\TikTok\tiknew\index.js:77:89
 >    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Gimenz** [comment]
some problem on tiktok api to get video list

**Comment by arifals27** [comment]
change this code
`if (videoList !== undefined) {`
to this
`if (videoList !== undefined || videoList.length > 0) {`
on line 79 at index.js

**Comment by snapboss** [comment]
> change this code `if (videoList !== undefined) {` to this `if (videoList !== undefined || videoList.length > 0) {` on line 79 at index.js

Thank you, The new update from @Gimenz and your code fixed this :)
